# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'coloringbook' do
  use_frameworks!
  pod 'SDWebImage', '~> 4.0'
  pod 'SwiftyStoreKit', '~> 0.8'

pod 'AFNetworking'
pod 'JPush'

end
